export interface Item { k?: string; t: string; d?: string }
export interface SlideData {
  id: string; title: string; layout: 'title' | 'statement' | 'cards' | 'steps' | 'bullets' | 'rows';
  dark: boolean; kicker?: string; heading: string; sub?: string; lines?: string[]; items?: Item[];
  foot?: string; image?: 'portrait'; mono?: boolean; question?: boolean; notes: string;
}

export const slides: SlideData[] = [
  { id: 'opening', title: 'From Zero to Contributor', layout: 'title', dark: true, kicker: 'OPEN SOURCE KIGALI // ALU EDITION', heading: 'From Zero to Contributor', sub: 'Git, GitHub, and the habits that turn code into a career.', foot: 'Led by Ub-Victor · Live demo + real projects', notes: 'Welcome. Set the promise: you will open a GitHub tab and ship something real, in under 10 minutes.' },
  { id: 'speaker', title: 'Who is speaking', layout: 'statement', dark: false, kicker: 'WHO IS TALKING', heading: 'I am not here to impress you. I am here to move you.', lines: ['Ushindi Victoire', 'Open Source Kigali contributor · Software engineer', 'In the next 20 minutes you will not watch me code. You will open a GitHub tab and ship something real.'], image: 'portrait', notes: 'Keep this short. One sentence about yourself, then move on.' },
  { id: 'promise', title: 'The promise', layout: 'cards', dark: true, kicker: 'THE DEAL', heading: 'What you walk out with', items: [{ k: '01', t: 'A merged-ready Pull Request', d: 'Made live, by you, today.' }, { k: '02', t: 'A real issue to work on', d: "From OSK's own repos." }, { k: '03', t: 'A daily system', d: 'Discipline that survives bad moods.' }], foot: 'If you leave with only notes, this session failed.', notes: 'Say the three outcomes out loud. Then the last line, slowly.' },
  { id: 'rules', title: 'Session rules', layout: 'bullets', dark: false, kicker: 'KEEP IT ALIVE', heading: 'House rules for the next 17 minutes', lines: ['Ask the question the moment it appears in your head.', 'Laptop open. Hands on keyboard. Not later, now.', 'Confused is allowed. Silent and confused is not.'], notes: 'Invite questions throughout. Confirm everyone has a laptop and a GitHub account (or can create one now).' },
  { id: 'git-vs-github', title: 'Git vs GitHub', layout: 'cards', dark: true, kicker: 'PHASE 4 · LIVE', heading: 'Git is not GitHub', items: [{ k: 'GIT', t: 'The tool on your machine', d: 'Saves versions of your work. Works offline. It is the camera taking photos of your code.' }, { k: 'GITHUB', t: 'The place on the internet', d: 'Stores those photos, shows them to the world, and lets people work on them with you.' }], foot: 'Git = the skill. GitHub = the stage.', notes: 'Analogy: camera vs gallery. Live demo starts here (2:30–2:50, led by Ub-Victor).' },
  { id: 'path', title: 'The Contribution Path', layout: 'steps', dark: false, kicker: 'WATCH, THEN DO', heading: 'The 10-minute contribution path', items: [{ k: '1', t: 'Account' }, { k: '2', t: 'Fork' }, { k: '3', t: 'Clone' }, { k: '4', t: 'Branch' }, { k: '5', t: 'Change' }, { k: '6', t: 'Commit' }, { k: '7', t: 'Push' }, { k: '8', t: 'Pull Request' }], foot: 'No permission needed. No invitation. The button is public. Most people never press it.', notes: 'Fork gives you your own copy (origin). The original project is upstream.' },
  { id: 'live', title: 'Screen on. Talking off.', layout: 'statement', dark: true, kicker: 'LIVE NOW', heading: 'Screen on. Talking off.', sub: 'Fork → Clone → Branch → Change → Commit → Push → Pull Request', notes: 'Switch to the browser and terminal. Do the real actions; do not over-explain.' },
  { id: 'commands', title: 'Command cheat sheet', layout: 'rows', dark: false, mono: true, kicker: 'KEEP THIS PHOTO', heading: 'The only commands you need today', items: [{ k: 'git clone <url>', t: 'Bring the project to your laptop' }, { k: 'git switch -c fix/typo', t: 'Create your own safe lane' }, { k: 'git add . && git commit -m "..."', t: 'Save the work with a clear message' }, { k: 'git push -u origin fix/typo', t: 'Send it to your fork on GitHub' }, { k: 'Open Pull Request', t: 'Ask the project to take your change' }], notes: 'Press C for the full command reference with copy buttons. Check git status before git add .' },
  { id: 'milestone', title: 'Contributor milestone', layout: 'statement', dark: true, kicker: 'MILESTONE', heading: 'You are now, officially, an open source contributor.', sub: 'It took under 10 minutes. The gap was never talent. It was the first click.', notes: 'Pause. Let it land.' },
  { id: 'question', title: 'Do I need to be good first?', layout: 'statement', dark: false, question: true, kicker: 'QUESTION FROM THE ROOM', heading: '“Do I need to be good first?”', lines: ['No. You become good BY contributing. Reading code you did not write is the fastest teacher alive.', 'Your first PR can be a typo. Your fifth will be a bug. Your twentieth will be a feature. Nobody starts at twenty.'], notes: 'Ask the room first and let two people answer. Then reveal (press Space / Right).' },
  { id: 'showcase', title: 'Project showcase', layout: 'statement', dark: true, kicker: 'PHASE 5 · 2:51–3:10', heading: 'Real problems. Real repos. Starting today.', notes: 'These are real problems you can start working on today.' },
  { id: 'repos', title: 'Open Source Kigali repositories', layout: 'cards', dark: false, kicker: 'WHERE TO START', heading: 'Open Source Kigali repositories', items: [{ k: 'osk-frontend', t: 'React 19 · TypeScript · Tailwind · Vite', d: 'The community website. UI fixes, responsiveness, accessibility, new sections.' }, { k: 'osk-backend', t: 'Express · TypeScript · Prisma · PostgreSQL', d: 'The API behind it. Validation, tests, docs, endpoints, error handling.' }], foot: 'github.com/Open-Source-Kigali', notes: 'Open both repos live. Read CONTRIBUTING.md first: it beats any generic advice. NOTE: the CV lists the OSK backend as NestJS; the original deck says Express. Confirm before presenting.' },
  { id: 'first-issue', title: 'How to choose a first issue', layout: 'bullets', dark: true, kicker: 'DO THIS TONIGHT', heading: 'How to pick your first issue', lines: ['Filter labels: good first issue, documentation, bug.', 'Read the issue twice. Comment: “I would like to work on this.”', 'Reproduce it before you fix it. Understanding beats guessing.', 'Small and finished beats big and abandoned.'], foot: 'One issue per week for a month = 4 public proofs that you can work with others.', notes: 'Show the Issues tab and the label filter on a real OSK repo.' },
  { id: 'discipline', title: 'Motivation vs discipline', layout: 'cards', dark: false, kicker: 'THE REAL ENGINEERING SKILL', heading: 'Motivation vs Discipline', items: [{ k: 'MOTIVATION', t: 'A feeling', d: 'It shows up after a good video and leaves when you are tired, broke or bored.' }, { k: 'DISCIPLINE', t: 'A decision already made', d: 'You code at 20:00 whether or not you feel like a genius.' }], foot: 'Motivation gets you to the event. Discipline gets you to the job.', notes: 'Discipline is more reliable than temporary motivation.' },
  { id: 'theory', title: 'Life is not theory', layout: 'cards', dark: true, kicker: 'THEORY → PRACTICE', heading: 'Life is not theory', sub: 'But theory, well accumulated, makes practice easy.', items: [{ k: '0 projects', t: 'Watched 40 hours of tutorials', d: 'You know about code.' }, { k: '4 projects', t: 'Watched 4 hours, built 4 things', d: 'You can write code.' }], foot: 'Learn just enough to build the next thing. Then build it.', notes: 'Theory should make practice easier, not replace it.' },
  { id: 'prepared', title: 'Opportunity favours the prepared', layout: 'cards', dark: false, kicker: 'HARD TRUTH', heading: 'Opportunity favours the prepared', sub: '“We need someone who can fix our website by Friday.”', items: [{ k: 'PREPARED', t: 'Shows a GitHub profile', d: 'Gets paid.' }, { k: 'NOT PREPARED', t: 'Says “give me two months”', d: 'Gets nothing.' }], foot: 'Chance visits everyone. It only stays where there is proof.', notes: 'Same chance, two people. Ask the room which one they want to be.' },
  { id: 'ai', title: 'Coding is practical — AI is the trap', layout: 'bullets', dark: true, kicker: "USE IT, DON'T OUTSOURCE TO IT", heading: 'Coding is practical. AI is the trap when it replaces thinking.', lines: ['AI removes the struggle. The struggle was the training.', 'If you never sit with a bug, you never build debugging muscle.', 'Rule: try it yourself first, then ask AI to review, not to replace.', 'Always be able to explain, line by line, the code you submit.'], foot: 'AI should be your gym partner, not your body.', notes: 'Gym partner, not a replacement for your mental muscles.' },
  { id: 'imposter', title: 'Imposter syndrome', layout: 'cards', dark: false, kicker: 'YOU ARE NOT ALONE IN THIS ROOM', heading: 'Imposter syndrome', sub: 'The feeling that you do not belong here, and someone will soon find out.', items: [{ t: '“Everyone is ahead of me”', d: 'You compare your day 1 to their year 5.' }, { t: '“I got lucky”', d: 'You discount work you actually did.' }, { t: "“I can't ask, they'll know”", d: 'Silence becomes your ceiling.' }], foot: 'Feeling like a fraud is common. Staying quiet about it is the real problem.', notes: 'Name it, normalise it. Keep it light.' },
  { id: 'overcome', title: 'Four ways to beat imposter syndrome', layout: 'cards', dark: true, kicker: 'FOUR MOVES', heading: 'How to beat it, practically', items: [{ k: '1', t: 'Keep receipts', d: "A file of every PR, issue and fix. Feelings lie, logs don't." }, { k: '2', t: 'Ship in public', d: 'One small commit is louder than one big plan.' }, { k: '3', t: 'Ask the dumb question', d: 'The room is always thinking it too.' }, { k: '4', t: 'Teach it back', d: "Explain today's demo to a friend tonight." }], foot: 'Confidence is a side effect of evidence.', notes: 'Evidence, practice, public work, questions, teaching.' },
  { id: 'dream', title: 'Stop dreaming; start living', layout: 'statement', dark: false, kicker: 'STOP DREAMING', heading: 'Start living one of them.', sub: 'We do not become what we want to be. We become what we do, daily, until it is who we are.', foot: 'A dreamer has plans. An engineer has commits.', notes: 'We become what we repeatedly do while moving toward who we want to become.' },
  { id: 'challenge', title: 'Seven-day contributor challenge', layout: 'rows', dark: true, kicker: 'LEAVE WITH A PLAN, NOT A FEELING', heading: 'The 7-day challenge', items: [{ k: 'Day 1', t: "Finish today's PR. Share the link." }, { k: 'Day 2-3', t: 'Claim one good first issue on an OSK repo.' }, { k: 'Day 4-5', t: 'Reproduce it, fix it, open the PR.' }, { k: 'Day 6', t: "Review someone else's PR and comment." }, { k: 'Day 7', t: 'Write 5 lines about what you learned. Post it.' }], notes: 'Ask people to screenshot this slide.' },
  { id: 'your-turn', title: 'Your turn', layout: 'statement', dark: true, kicker: 'YOUR TURN', heading: 'The repos are open. The issues are real. The only missing commit is yours.', sub: 'github.com/Open-Source-Kigali', foot: 'Questions? Now is the cheapest they will ever be.', notes: 'Close with the call to action. Take questions.' },
];
